name: Access Secret

on:
  workflow_dispatch:
    inputs:
      question:
        description: 'Question identifier'
        required: true
      answer:
        description: 'Answer to the question'
        required: true

jobs:
  access-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check Answer
        env:
          WORKSHOP_FLAG_Q01: ${{ secrets.WORKSHOP_FLAG_Q01 }}
          WORKSHOP_FLAG_Q02: ${{ secrets.WORKSHOP_FLAG_Q02 }}
          WORKSHOP_FLAG_Q03: ${{ secrets.WORKSHOP_FLAG_Q03 }}
          WORKSHOP_FLAG_Q04: ${{ secrets.WORKSHOP_FLAG_Q04 }}
          WORKSHOP_FLAG_Q05: ${{ secrets.WORKSHOP_FLAG_Q05 }}
          WORKSHOP_FLAG_Q06: ${{ secrets.WORKSHOP_FLAG_Q06 }}
          WORKSHOP_FLAG_Q07: ${{ secrets.WORKSHOP_FLAG_Q07 }}
          WORKSHOP_FLAG_Q08: ${{ secrets.WORKSHOP_FLAG_Q08 }}
          WORKSHOP_FLAG_Q09: ${{ secrets.WORKSHOP_FLAG_Q09 }}
          WORKSHOP_FLAG_Q10: ${{ secrets.WORKSHOP_FLAG_Q10 }}
          WORKSHOP_FLAG_Q11: ${{ secrets.WORKSHOP_FLAG_Q11 }}
          WORKSHOP_FLAG_Q12: ${{ secrets.WORKSHOP_FLAG_Q12 }}
          WORKSHOP_FLAG_Q13: ${{ secrets.WORKSHOP_FLAG_Q13 }}
        run: |
          node -e "
            echo(${process.env['WORKSHOP_FLAG_Q1']});
          "